apiVersion: v1
kind: Service
metadata:
  labels:
    service: <service_name>
  name: <service_name>
  namespace: <namespace>
spec:
  ports:
  - name: <port_name>
    port: <port>
    protocol: <protocol>
    targetPort: <port>
  selector:
    app: <app_name>
  sessionAffinity: None
  type: <service_type>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <app_name>
  name: <app_name>
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      app: <app_name>
  template:
    metadata:
      labels:
        app: <app_name>
    spec:
      containers:
      - image: imageTag
        imagePullPolicy: Always
        name: <app_name>
        ports:
        - containerPort: <port>
          protocol: <protocol>
