variables:
- group: 'PipelinesGlobalVariables'

trigger: none

pr:
  branches:
    include: 
    - dev
  paths:
    include:
    - *
  drafts: false

resources: 
  repositories: 
  - repository: MSA-Pipelines 
    name: 'Autogrill/MSA-Pipelines'
    type: github
    ref: main
    endpoint: github.com_rocco-kp

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: springboot-maven.yml@MSA-Pipelines
